language: go
sudo: false
addons:
  apt:
    packages:
      - libasound2-dev

go:
- 1.17
install:
- go get -d -t -v ./...

script:
- make test
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go run cmd/build/build.go
  - cd dist && sha512sum * > checksum

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bbn0U42cMuDYAQGCMaPXbkTOygk3Sr/P8u998Y13RVFEe/rcM4UQ9WjvhOMFlMLS3gN6Gqu/Qm3cT5z4AawY0JPf1PnbGprTMCZEzrHPmd203cAMRmcpzTYBEkioRRTgOS5syVxxY8ZNKCW4+/QAmngai3uU/CL/4aPL5T6SQSk=
  file_glob: true
  file: "*"
  on:
    tags: true
    repo: stampzilla/stampzilla-go
    condition: $TRAVIS_GO_VERSION =~ ^1\.17
